#!/bin/bash

for run in {1..30}
do
    echo "Iteration: $run"

    python train.py \
            --dataset ms_academic_phy \
            --checkpt_file pre_trained/ms_academic_phy/ms_academic_phy_mod.ckpt \
            --train_size 5 \
            --dropout 0.6 \
            --seed $run \
	    >> odnn_ms_academic_phy_5.txt
done

# python calculate_average_accuracy.py \
#         --file_name odnn_ms_academic_phy_5.txt \
